package app.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary_oc = Color(0xFF13458E)
val md_theme_light_onPrimary_oc = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer_oc = Color(0xFFD8E2FF)
val md_theme_light_onPrimaryContainer_oc = Color(0xFF001A41)
val md_theme_light_secondary_oc = Color(0xFF285EA7)
val md_theme_light_onSecondary_oc = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer_oc = Color(0xFFD6E3FF)
val md_theme_light_onSecondaryContainer_oc = Color(0xFF001B3D)
val md_theme_light_tertiary_oc = Color(0xFF0861A4)
val md_theme_light_onTertiary_oc = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer_oc = Color(0xFFD2E4FF)
val md_theme_light_onTertiaryContainer_oc = Color(0xFF001D37)
val md_theme_light_error_oc = Color(0xFFBA1A1A)
val md_theme_light_errorContainer_oc = Color(0xFFFFDAD6)
val md_theme_light_onError_oc = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer_oc = Color(0xFF410002)
val md_theme_light_background_oc = Color(0xFFFEFBFF)
val md_theme_light_onBackground_oc = Color(0xFF1B1B1F)
val md_theme_light_surface_oc = Color(0xFFFEFBFF)
val md_theme_light_onSurface_oc = Color(0xFF1B1B1F)
val md_theme_light_surfaceVariant_oc = Color(0xFFF5F5F5)
val md_theme_light_onSurfaceVariant_oc = Color(0xFF44474F)
val md_theme_light_outline_oc = Color(0xFF75777F)
val md_theme_light_inverseOnSurface_oc = Color(0xFFF2F0F4)
val md_theme_light_inverseSurface_oc = Color(0xFF303033)
val md_theme_light_inversePrimary_oc = Color(0xFFADC6FF)
val md_theme_light_shadow_oc = Color(0xFF000000)
val md_theme_light_surfaceTint_oc = Color(0xFF315DA8)
val md_theme_light_outlineVariant_oc = Color(0xFFC4C6D0)
val md_theme_light_scrim_oc = Color(0xFF000000)

val md_theme_dark_primary_oc = Color(0xFFadc6ff)
val md_theme_dark_onPrimary_oc = Color(0xFF002E69)
val md_theme_dark_primaryContainer_oc = Color(0xFF0F448F)
val md_theme_dark_onPrimaryContainer_oc = Color(0xFFD8E2FF)
val md_theme_dark_secondary_oc = Color(0xFF313141)
val md_theme_dark_onSecondary_oc = Color(0xFF003063)
val md_theme_dark_secondaryContainer_oc = Color(0xFF00468B)
val md_theme_dark_onSecondaryContainer_oc = Color(0xFFD6E3FF)
val md_theme_dark_tertiary_oc = Color(0xFF9FCAFF)
val md_theme_dark_onTertiary_oc = Color(0xFF003259)
val md_theme_dark_tertiaryContainer_oc = Color(0xFF00497E)
val md_theme_dark_onTertiaryContainer_oc = Color(0xFFD2E4FF)
val md_theme_dark_error_oc = Color(0xFFBA1A1A)
val md_theme_dark_errorContainer_oc = Color(0xFF93000A)
val md_theme_dark_onError_oc = Color(0xFF690005)
val md_theme_dark_onErrorContainer_oc = Color(0xFFFFDAD6)
val md_theme_dark_background_oc = Color(0xFF1B1B1F)
val md_theme_dark_onBackground_oc = Color(0xFFE3E2E6)
val md_theme_dark_surface_oc = Color(0xFF1B1B1F)
val md_theme_dark_onSurface_oc = Color(0xFFE3E2E6)
val md_theme_dark_surfaceVariant_oc = Color(0xFF2D2D2D)
val md_theme_dark_onSurfaceVariant_oc = Color(0xFFC4C6D0)
val md_theme_dark_outline_oc = Color(0xFF8E9099)
val md_theme_dark_inverseOnSurface_oc = Color(0xFF1B1B1F)
val md_theme_dark_inverseSurface_oc = Color(0xFFE3E2E6)
val md_theme_dark_inversePrimary_oc = Color(0xFF315DA8)
val md_theme_dark_shadow_oc = Color(0xFF000000)
val md_theme_dark_surfaceTint_oc = Color(0xFFADC6FF)
val md_theme_dark_outlineVariant_oc = Color(0xFF44474F)
val md_theme_dark_scrim_oc = Color(0xFF000000)

val seed_oc = Color(0xFF13458E)
